services:
  - type: web
    name: kerental-backend
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
      - key: PAKASIR_API_KEY
        sync: false
      - key: PAKASIR_PROJECT_SLUG
        sync: false
    healthCheckPath: /
